[package]
name = "remouse"
version = "0.1.0"
authors = ["William Henderson <william-henderson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiinput = "0.1.0"
enigo = "0.0.14"
minifb = "0.10.6"